version: '3.7'

services: 
# Directories are relative to the docker-compose.yml file.
    users:
        build: 
            context: ./services/users
            dockerfile: Dockerfile-prod
        ports: 
            - 5001:5000
        environment: 
            - PLASK_ENV=production
            - APP_SETTINGS=project.config.ProductionConfig
            - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
            - DATDATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
        depends_on: 
            - users-db

    users-db:  # new
        build:
            context: ./services/users/project/db
            dockerfile: Dockerfile
        ports:
            - 5435:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
