version: '3.7'

services: 
# Directories are relative to the docker-compose.yml file.
    users:
        build: 
            context: ./services/users
            dockerfile: Dockerfile
        volumes: 
            - './services/users:/usr/src/app'
        ports: 
            - 5001:5000
        environment: 
            - FLASK_APP=project/__init__.py
            - PLASK_ENV=development
            - APP_SETTINGS=project.config.DevelopmentConfig
